### ISSUE TITLE
Renaming repository from now-rust to vercel-rust

### ISSUE THREAD

**Issue by nico-bachner** [mike-engel/vercel-rust#33]
Since ZEIT has recently rebranded as Vercel, it seems adequate that we rename the repository accordingly.

I assume simply changing the name will break some things, so if someone would be so kind as to list the possible breaking points, I will do my best to deal with them.

**Comment by mike-engel** [comment]
Waiting for a reply from https://github.com/gogenhub/vercel-rust/issues/1

**Comment by mike-engel** [comment]
This has now complete! `vercel-rust` is now available on npm as version `3.0.0`.
