### ISSUE TITLE
Using now@16.1.1 prints a lot of errors

### ISSUE THREAD

**Issue by cbrevik** [mike-engel/vercel-rust#6]
**Describe the bug**
Using the command `now dev` with `now@16.1.1` prints a lot of file related errors. Mostly "too many open files". It keeps printing that until I kill the process. 

This does not happen with a pre-16 `now` version, e.g. `now@15.8.7`

**To Reproduce**
* Clone example project: https://github.com/cbrevik/now-rust-test/tree/bd68edc3aa2440d17537af0b772770c68cfa21e7
* Install `yarn global add now@16.1.1`
* Run `now dev`

**Expected behavior**
No errors.

**Logs**
> Ready! Available at http://localhost:3002
2019-08-19 19:43 node[25928] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2019-08-19 19:43 node[25928] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
> Error! Watcher error: Error: EMFILE: too many open files, watch

![image](https://user-images.githubusercontent.com/4932625/63287430-97eb5a00-c2ba-11e9-9ccd-d239bed0da2a.png)

**Environment (please complete the following information):**
 - rust: stable `1.37.0`
 - rust edition: 2018
 - now-rust: latest

**Additional context**
None.

**Comment by mike-engel** [comment]
Is this with a `Cargo.toml`, `*.rs`, or something other entry point? Or a combo of those?

**Comment by cbrevik** [comment]
In the example project it is a single `*.rs`, but this also happens with a `Cargo.toml` as entry point.

**Comment by mike-engel** [comment]
@cbrevik does this still happen with the latest version of `now` for you? Sorry I can't test myself right now—life is keeping me very busy!

**Comment by cbrevik** [comment]
Updated to now `16.1.2` and tried again now @mike-engel - still getting the same error

**Comment by mike-engel** [comment]
Hi @cbrevik I'm sorry I've let this lag. If you're still using this project, does it still happen with vercel?

**Comment by cbrevik** [comment]
Hi @mike-engel! I decided to try Rust in other contexts instead, so I haven't used this project since last. I'm sure this issue can be closed if you're not using it to track a verified bug 👍🏻

**Comment by mike-engel** [comment]
Thanks for the reply!
