### ISSUE TITLE
rust function beside node.js function not working...

### ISSUE THREAD

**Issue by corentinway** [mike-engel/vercel-rust#8]
**Describe the bug**
I cannot deploy a serverless rust function beside a node.js function

**To Reproduce**
deploy on now the sample : https://github.com/corentinway/now-rust-playground 

**Expected behavior**
no issue, rust function working

**Logs**
preparing cache...

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at Object.prepareCache (/tmp/98fc514d9a3f3ae5/.build-utils/.builder/node_modules/now-rust/dist/index.js:227:51)
    at uploadCacheStep (/var/task/sandbox-worker.js:26330:55)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

**Environment (please complete the following information):**
 - rust stable
 - rust edition 2018
 - now-rust latest

**Additional context**

**Comment by mike-engel** [comment]
Hi @corentinway! You wrote in the issue above that this isn't a problem with now-rust, as that part is working fine. Is that correct? Does this happen when deploying, or during `now dev`? Does this happen every time or only when deployed with a node.js lambda?

**Comment by mike-engel** [comment]
Closing until more info is provided.
